export const mockDiseases = [
  {
    id: '1',
    name: 'Common Cold',
    definition: 'A viral infection of the upper respiratory tract affecting the nose and throat.',
    symptoms: ['Runny nose', 'Sore throat', 'Cough', 'Sneezing', 'Mild fever'],
    causes: ['Rhinoviruses', 'Coronaviruses', 'Close contact with infected persons'],
    testsAndProcedures: ['Physical examination', 'Throat swab (if needed)'],
    medications: ['Acetaminophen', 'Ibuprofen', 'Decongestants', 'Antihistamines'],
    treatments: ['Rest', 'Fluids', 'Over-the-counter medications'],
    prevention: ['Wash hands frequently', 'Avoid close contact with sick people', 'Disinfect surfaces'],
    prognosis: 'Usually resolves within 7-10 days without complications.',
    severity: 'Mild',
    category: 'Respiratory',
    prevalence: 'Very Common'
  },
  {
    id: '2',
    name: 'Influenza (Flu)',
    definition: 'A contagious respiratory illness caused by influenza viruses that infect the nose, throat, and lungs.',
    symptoms: ['High fever', 'Body aches', 'Fatigue', 'Dry cough', 'Headache', 'Chills'],
    causes: ['Influenza A virus', 'Influenza B virus', 'Airborne transmission'],
    testsAndProcedures: ['Rapid influenza diagnostic test', 'RT-PCR test', 'Viral culture'],
    medications: ['Oseltamivir (Tamiflu)', 'Zanamivir', 'Acetaminophen'],
    treatments: ['Antiviral medications', 'Rest', 'Fluids'],
    prevention: ['Annual flu vaccination', 'Hand hygiene', 'Avoid crowded places during flu season'],
    prognosis: 'Most people recover within 1-2 weeks. High-risk groups may develop complications.',
    severity: 'Moderate',
    category: 'Respiratory',
    prevalence: 'Common'
  },
  {
    id: '3',
    name: 'Migraine',
    definition: 'A neurological condition characterized by intense, debilitating headaches often accompanied by other symptoms.',
    symptoms: ['Severe headache', 'Nausea', 'Light sensitivity', 'Sound sensitivity', 'Visual disturbances'],
    causes: ['Genetic factors', 'Hormonal changes', 'Stress', 'Certain foods', 'Sleep changes'],
    testsAndProcedures: ['Neurological examination', 'MRI', 'CT scan'],
    medications: ['Triptans', 'NSAIDs', 'Anti-nausea medications', 'Preventive medications'],
    treatments: ['Pain relief medications', 'Rest in dark room', 'Preventive therapy'],
    prevention: ['Identify and avoid triggers', 'Regular sleep schedule', 'Stress management'],
    prognosis: 'Chronic condition that can be managed with proper treatment and lifestyle changes.',
    severity: 'Moderate',
    category: 'Neurological',
    prevalence: 'Common'
  },
  {
    id: '4',
    name: 'Type 2 Diabetes',
    definition: 'A chronic metabolic condition affecting how the body processes blood sugar (glucose).',
    symptoms: ['Increased thirst', 'Frequent urination', 'Fatigue', 'Blurred vision', 'Slow healing wounds'],
    causes: ['Insulin resistance', 'Obesity', 'Sedentary lifestyle', 'Genetic factors'],
    testsAndProcedures: ['Fasting blood glucose test', 'HbA1c test', 'Oral glucose tolerance test'],
    medications: ['Metformin', 'Sulfonylureas', 'Insulin', 'GLP-1 agonists'],
    treatments: ['Lifestyle modifications', 'Oral medications', 'Insulin therapy'],
    prevention: ['Maintain healthy weight', 'Regular exercise', 'Balanced diet'],
    prognosis: 'Lifelong condition requiring ongoing management. Well-controlled diabetes has good outcomes.',
    severity: 'Severe',
    category: 'Metabolic',
    prevalence: 'Common'
  },
  {
    id: '5',
    name: 'Hypertension',
    definition: 'A chronic condition where blood pressure against artery walls is consistently too high.',
    symptoms: ['Headaches', 'Shortness of breath', 'Nosebleeds', 'Chest pain', 'Often asymptomatic'],
    causes: ['Unhealthy diet', 'Lack of exercise', 'Obesity', 'Stress', 'Genetics'],
    testsAndProcedures: ['Blood pressure measurement', 'Blood tests', 'ECG', 'Echocardiogram'],
    medications: ['ACE inhibitors', 'Beta blockers', 'Diuretics', 'Calcium channel blockers'],
    treatments: ['Lifestyle changes', 'Antihypertensive medications', 'Regular monitoring'],
    prevention: ['Reduce salt intake', 'Exercise regularly', 'Maintain healthy weight', 'Limit alcohol'],
    prognosis: 'Can be effectively managed with medication and lifestyle changes. Uncontrolled hypertension increases risk of heart disease and stroke.',
    severity: 'Severe',
    category: 'Cardiovascular',
    prevalence: 'Very Common'
  },
  {
    id: '6',
    name: 'Allergic Rhinitis',
    definition: 'An allergic response causing inflammation of the nasal passages, commonly known as hay fever.',
    symptoms: ['Sneezing', 'Runny nose', 'Itchy eyes', 'Nasal congestion', 'Watery eyes'],
    causes: ['Pollen', 'Dust mites', 'Pet dander', 'Mold spores'],
    testsAndProcedures: ['Skin prick test', 'Blood test for IgE antibodies', 'Nasal endoscopy'],
    medications: ['Antihistamines', 'Nasal corticosteroids', 'Decongestants', 'Immunotherapy'],
    treatments: ['Allergen avoidance', 'Medications', 'Allergy shots'],
    prevention: ['Avoid known allergens', 'Keep windows closed during high pollen', 'Use air purifiers'],
    prognosis: 'Chronic condition that can be well-managed with proper treatment and allergen avoidance.',
    severity: 'Mild',
    category: 'Respiratory',
    prevalence: 'Very Common'
  }
];

export const mockMedications = [
  {
    id: '1',
    name: 'Acetaminophen (Tylenol)',
    purpose: 'Pain reliever and fever reducer used for mild to moderate pain and fever.',
    disease: ['Common Cold', 'Influenza', 'Migraine'],
    sideEffects: 'Nausea, stomach pain, loss of appetite. Rare: liver damage with overdose.',
    dosage: ['325mg every 4-6 hours', '500mg every 4-6 hours', '650mg every 4-6 hours'],
    contraindications: ['Liver disease', 'Alcohol use disorder', 'Allergy to acetaminophen'],
    interactions: ['Warfarin', 'Alcohol', 'Other acetaminophen products'],
    howItWorks: 'Reduces pain signals in the brain and lowers body temperature by affecting the hypothalamus.',
    whenToTake: 'Take as needed for pain or fever. Can be taken with or without food.',
    warnings: ['Do not exceed 4000mg per day', 'Avoid alcohol', 'Check other medications for acetaminophen'],
    category: 'Analgesic'
  },
  {
    id: '2',
    name: 'Ibuprofen (Advil, Motrin)',
    purpose: 'Nonsteroidal anti-inflammatory drug (NSAID) for pain, inflammation, and fever.',
    disease: ['Migraine', 'Common Cold', 'Allergic Rhinitis'],
    sideEffects: 'Upset stomach, heartburn, dizziness, nausea. Rare: stomach bleeding, kidney problems.',
    dosage: ['200mg every 4-6 hours', '400mg every 4-6 hours', '600mg every 6-8 hours'],
    contraindications: ['Stomach ulcers', 'Kidney disease', 'Heart disease', 'Aspirin allergy'],
    interactions: ['Aspirin', 'Blood thinners', 'ACE inhibitors', 'Lithium'],
    howItWorks: 'Blocks enzymes (COX-1 and COX-2) that produce prostaglandins, reducing inflammation and pain.',
    whenToTake: 'Take with food or milk to reduce stomach upset.',
    warnings: ['Take with food', 'May increase bleeding risk', 'Avoid in third trimester of pregnancy'],
    category: 'NSAID'
  },
  {
    id: '3',
    name: 'Metformin (Glucophage)',
    purpose: 'First-line medication for type 2 diabetes to control blood sugar levels.',
    disease: ['Type 2 Diabetes'],
    sideEffects: 'Nausea, diarrhea, stomach upset, metallic taste. Rare: lactic acidosis.',
    dosage: ['500mg twice daily', '850mg twice daily', '1000mg twice daily'],
    contraindications: ['Kidney disease', 'Liver disease', 'Heart failure', 'Metabolic acidosis'],
    interactions: ['Contrast dye', 'Alcohol', 'Certain diuretics'],
    howItWorks: 'Decreases glucose production in the liver and improves insulin sensitivity in muscles.',
    whenToTake: 'Take with meals to reduce stomach side effects. Usually taken twice daily.',
    warnings: ['Take with meals', 'Monitor kidney function', 'Stop before contrast imaging'],
    category: 'Antidiabetic'
  },
  {
    id: '4',
    name: 'Lisinopril (Prinivil, Zestril)',
    purpose: 'ACE inhibitor for high blood pressure and heart failure.',
    disease: ['Hypertension'],
    sideEffects: 'Dry cough, dizziness, headache, fatigue. Rare: angioedema, high potassium.',
    dosage: ['5mg once daily', '10mg once daily', '20mg once daily', '40mg once daily'],
    contraindications: ['Pregnancy', 'History of angioedema', 'Bilateral renal artery stenosis'],
    interactions: ['Potassium supplements', 'NSAIDs', 'Lithium', 'Aliskiren'],
    howItWorks: 'Blocks ACE enzyme, reducing angiotensin II production, which relaxes blood vessels.',
    whenToTake: 'Take once daily at the same time each day. Can be taken with or without food.',
    warnings: ['Avoid during pregnancy', 'Monitor potassium levels', 'May cause dizziness when standing'],
    category: 'Antihypertensive'
  },
  {
    id: '5',
    name: 'Cetirizine (Zyrtec)',
    purpose: 'Second-generation antihistamine for allergies and hay fever.',
    disease: ['Allergic Rhinitis'],
    sideEffects: 'Drowsiness, dry mouth, fatigue, headache.',
    dosage: ['5mg once daily', '10mg once daily'],
    contraindications: ['Severe kidney disease', 'Allergy to cetirizine or hydroxyzine'],
    interactions: ['Alcohol', 'CNS depressants', 'Theophylline'],
    howItWorks: 'Blocks histamine H1 receptors, preventing allergic symptoms like sneezing and itching.',
    whenToTake: 'Take once daily. Can be taken with or without food.',
    warnings: ['May cause drowsiness', 'Avoid alcohol', 'Use caution when driving'],
    category: 'Antihistamine'
  }
];
