export const mockDiseases = [
  {
    id: '1',
    name: 'Common Cold',
    description: 'A viral infection of the upper respiratory tract',
    symptoms: ['Runny nose', 'Sore throat', 'Cough', 'Sneezing', 'Mild fever'],
    severity: 'MILD' as const,
    category: 'Respiratory',
    prevalence: 'VERY_COMMON' as const,
    contagious: true,
    chronicCondition: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '2',
    name: 'Influenza (Flu)',
    description: 'A contagious respiratory illness caused by influenza viruses',
    symptoms: ['High fever', 'Body aches', 'Fatigue', 'Dry cough', 'Headache', 'Chills'],
    severity: 'MODERATE' as const,
    category: 'Respiratory',
    prevalence: 'COMMON' as const,
    contagious: true,
    chronicCondition: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '3',
    name: 'Migraine',
    description: 'A neurological condition characterized by intense headaches',
    symptoms: ['Severe headache', 'Nausea', 'Light sensitivity', 'Sound sensitivity', 'Visual disturbances'],
    severity: 'MODERATE' as const,
    category: 'Neurological',
    prevalence: 'COMMON' as const,
    contagious: false,
    chronicCondition: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '4',
    name: 'Type 2 Diabetes',
    description: 'A chronic condition affecting how the body processes blood sugar',
    symptoms: ['Increased thirst', 'Frequent urination', 'Fatigue', 'Blurred vision', 'Slow healing wounds'],
    severity: 'SEVERE' as const,
    category: 'Metabolic',
    prevalence: 'COMMON' as const,
    contagious: false,
    chronicCondition: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '5',
    name: 'Gastroenteritis',
    description: 'Inflammation of the digestive tract, often called stomach flu',
    symptoms: ['Diarrhea', 'Nausea', 'Vomiting', 'Abdominal cramps', 'Fever'],
    severity: 'MODERATE' as const,
    category: 'Digestive',
    prevalence: 'COMMON' as const,
    contagious: true,
    chronicCondition: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '6',
    name: 'Hypertension',
    description: 'High blood pressure, a chronic condition',
    symptoms: ['Headaches', 'Shortness of breath', 'Nosebleeds', 'Chest pain'],
    severity: 'SEVERE' as const,
    category: 'Cardiovascular',
    prevalence: 'VERY_COMMON' as const,
    contagious: false,
    chronicCondition: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '7',
    name: 'Allergic Rhinitis',
    description: 'Hay fever, an allergic response to allergens',
    symptoms: ['Sneezing', 'Runny nose', 'Itchy eyes', 'Nasal congestion'],
    severity: 'MILD' as const,
    category: 'Respiratory',
    prevalence: 'VERY_COMMON' as const,
    contagious: false,
    chronicCondition: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '8',
    name: 'Anxiety Disorder',
    description: 'A mental health condition characterized by excessive worry',
    symptoms: ['Excessive worry', 'Restlessness', 'Fatigue', 'Difficulty concentrating', 'Sleep problems'],
    severity: 'MODERATE' as const,
    category: 'Mental Health',
    prevalence: 'COMMON' as const,
    contagious: false,
    chronicCondition: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

export const mockMedications = [
  {
    id: '1',
    name: 'Acetaminophen',
    genericName: 'Paracetamol',
    brandNames: ['Tylenol', 'Panadol'],
    description: 'Pain reliever and fever reducer',
    dosageForm: 'Tablet',
    commonDosages: ['325mg', '500mg', '650mg'],
    usedFor: ['Pain relief', 'Fever reduction', 'Headache'],
    sideEffects: ['Nausea', 'Stomach pain', 'Loss of appetite'],
    warnings: ['Do not exceed 4000mg per day', 'Avoid alcohol'],
    requiresPrescription: false,
    category: 'Analgesic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '2',
    name: 'Ibuprofen',
    genericName: 'Ibuprofen',
    brandNames: ['Advil', 'Motrin'],
    description: 'Nonsteroidal anti-inflammatory drug (NSAID)',
    dosageForm: 'Tablet',
    commonDosages: ['200mg', '400mg', '600mg'],
    usedFor: ['Pain relief', 'Inflammation', 'Fever reduction'],
    sideEffects: ['Upset stomach', 'Heartburn', 'Dizziness'],
    warnings: ['Take with food', 'May increase bleeding risk'],
    requiresPrescription: false,
    category: 'NSAID',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '3',
    name: 'Metformin',
    genericName: 'Metformin',
    brandNames: ['Glucophage', 'Fortamet'],
    description: 'Medication for type 2 diabetes',
    dosageForm: 'Tablet',
    commonDosages: ['500mg', '850mg', '1000mg'],
    usedFor: ['Type 2 diabetes', 'Blood sugar control'],
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach upset'],
    warnings: ['Take with meals', 'Monitor kidney function'],
    requiresPrescription: true,
    category: 'Antidiabetic',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '4',
    name: 'Lisinopril',
    genericName: 'Lisinopril',
    brandNames: ['Prinivil', 'Zestril'],
    description: 'ACE inhibitor for high blood pressure',
    dosageForm: 'Tablet',
    commonDosages: ['5mg', '10mg', '20mg', '40mg'],
    usedFor: ['High blood pressure', 'Heart failure'],
    sideEffects: ['Dry cough', 'Dizziness', 'Headache'],
    warnings: ['Avoid during pregnancy', 'Monitor potassium levels'],
    requiresPrescription: true,
    category: 'Antihypertensive',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: '5',
    name: 'Cetirizine',
    genericName: 'Cetirizine',
    brandNames: ['Zyrtec', 'Reactine'],
    description: 'Antihistamine for allergies',
    dosageForm: 'Tablet',
    commonDosages: ['5mg', '10mg'],
    usedFor: ['Allergies', 'Hay fever', 'Hives'],
    sideEffects: ['Drowsiness', 'Dry mouth', 'Fatigue'],
    warnings: ['May cause drowsiness', 'Avoid alcohol'],
    requiresPrescription: false,
    category: 'Antihistamine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
